// ----------------------------------------------------------------------------
// <auto-generated>
// 		This code was generated by a tool on 04/04/2017 20:29:54.
//
//		Changes to this file may cause incorrect behavior and will be
// 			list if the code is re-generated.
//
// Output files: AssemblyInfo.cs and the configured nuspec file
// </auto-generated>
// ----------------------------------------------------------------------------
using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

// General Information about an assembly is controlled through the following
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("Newbe.CQP.Framework")]
[assembly: AssemblyDescription("酷Q(CoolQ) .net SDK from Newbe 帮助文档 http://yks.oschina.io/newbe.cqp.framework/?file=%E9%A6%96%E9%A1%B5")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Newbe")]
[assembly: AssemblyProduct("Newbe.CQP.Framework")]
[assembly: AssemblyCopyright("Copyright Newbe 2017")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

// Setting ComVisible to false makes the types in this assembly not visible
// to COM components.  If you need to access a type in this assembly from
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("88c3bb70-a79a-4e90-b994-a96766c2a4ac")]

[assembly: AssemblyVersion("1.0.0")]
[assembly: AssemblyFileVersion("1.0.0")]

